apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: selfsigned-issuer
    # Wachten
    argocd.argoproj.io/sync-wave: "5"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - longhorn.demo.local
      secretName: longhorn-tls
  rules:
    - host: longhorn.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: selfsigned-issuer
    argocd.argoproj.io/sync-wave: "5" # Wacht!
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grafana.demo.local
      secretName: grafana-tls
  rules:
    - host: grafana.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-ingress
  namespace: portainer
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: selfsigned-issuer
    argocd.argoproj.io/sync-wave: "5" # Wacht!
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - portainer.demo.local
      secretName: portainer-tls
  rules:
    - host: portainer.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 9443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd     # ArgoCD staat in zijn eigen namespace
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: selfsigned-issuer
    # ArgoCD stuurt zelf vaak al HTTPS, dit helpt Traefik het te begrijpen:
    traefik.ingress.kubernetes.io/router.tls: "true"
    argocd.argoproj.io/sync-wave: "5" # Wacht!
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argocd.demo.local
      secretName: argocd-secret-tls
  rules:
    - host: argocd.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443