# inventory.yml
---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.154.139: # Je Master node (kies er 1)
    agent:
      hosts:
        192.168.154.140:  # Worker 1
        192.168.154.141: # Worker 2
# ansible control node
ansible_control:
  hosts:
    localhost:
      ansible_connection: local

  # Algemene variabelen voor alle nodes
  vars:
    ansible_user: joeri  # <-- gebruikersnaam vms
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # Verwijst naar je key