# inventory.yml
---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.124.129: # Je Master node (kies er 1)
    agent:
      hosts:
        192.168.124.4:  # Worker 1
        192.168.124.7: # Worker 2

  # Algemene variabelen voor alle nodes
  vars:
    ansible_user: joeri  # <-- gebruikersnaam vms
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # Verwijst naar je key